### ISSUE TITLE
.temp_file_list: No such file or directory

### ISSUE THREAD

**Issue by kscavo23** [sheinasim/HiFiAdapterFilt#5]
Hi, 
I am trying to run HiFiAdapterFilt on a raw PacBio hifi .bam file using the following command:

bash pbadapterfilt.sh -p /path/to/bam/220209_hifi_reads.bam -o HiFiAdaptFilt_220209

and I keep getting the following error:
path/to/bam/220209_hifi_reads.bam.temp_file_list: No such file or directory

It seems to be making the output directory, but cuts out immediately. Do you know what could be going on here?

**Comment by mendezaranda** [comment]
Hi, I am having the same issue. Was this solved?
Best,
Daniel

**Comment by yasutoishii** [comment]
I encountered the same error. I created a symbolic link in the current directory, and run hifiadapterfilt without `-p` option, then the error was solved. I hope the same way will work for you!
Here is the example code.
```
cd /your/desired/directory/
ln -sf your/bam/file.bam
# -o and the log file is optional
bash hifiadapterfilt.sh -o output/name >hifiadapterfilt.log 2>&1
```

**Comment by mendezaranda** [comment]
Thank you! I'll try that
