### ISSUE TITLE
Blast database issue

### ISSUE THREAD

**Issue by kmkocot** [sheinasim/HiFiAdapterFilt#6]
Hi Sheina,

I was eager to try your adapter trimming tool but I experienced some issues I thought you might want to know about.

I noticed in the 2.0.0 release that line 6 is:
`DBpath=$(echo $PATH | sed 's/:/\n/g' | grep "HiFiAdapterFilt/DB" | head -n 1)`

However, I think it should be:
`DBpath=$(echo $PATH | sed 's/:/\n/g' | grep "HiFiAdapterFilt-2.0.0/DB" | head -n 1)`

That still isn't solving a problem I'm having, though. I'm consistently getting the following error unless I hard-code the path to the blast database:
```
BLAST Database error: No alias or index file found for nucleotide database [/pacbio_vectors_db] in search path [/grps2/kmk/2022-04-20_Ap212/PB744_AP212_5C_ULTP/r64069_20220330_183728/C1/outputs/adapter_filter_test::]
```

Also, do you know if the adapters used in the ultra-low PacBio library prep are the same as the ones in the pacbio_vectors_db file?

Thanks!
Kevin

**Comment by sheinasim** [comment]
Hello Kevin,

Sorry for the delay in my reply. 

The command to assign the path to the database should be:

`DBpath=$(echo $PATH | sed 's/:/\n/g' | grep "{Name of HiFiAdapterFilt directory}/DB" | head -n 1)`

I think I wrote it under the assumption that it would be cloned from github and thus the name should be HiFiAdapterFilt, but if it was downloaded from source and the directory name becomes HiFiAdapterFilt-2.0.0, then yes, please edit the script.

Some have had an issue with the database provided, to create the database, please make sure blast+ is in your path and use the command:

`makeblastdb -in [path to hifiadapterfilt]/DB/pacbio_vectors_db -dbtype nucl`

Best wishes,
Sheina
